# docker-compose.yml

version: '3'
services:
  service:
    build: app
    expose:
      - "8000"
    volumes:
      - static-vol:/opt/app/static
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "movies_database"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123qwe"
    ports:
      - "5432:5432"
    volumes:
       - ./app/dump/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static-vol:/data/static/:ro
    depends_on:
      - service
    ports:
      - "80:80"

volumes:
  static-vol: